alias pandoc-pdf="pandoc --mathjax --highlight-style tango --latex-engine=xelatex --template=/home/erlangz/.PanDoc/default.latex "
alias pandoc-html="pandoc --mathjax --highlight-style monochrome --css=/home/erlangz/.PanDoc/default.css "
